### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by AntseN** [crayner/CKEditor#2]
Hi there, thx btw for putting efforts in porting this bundle to symfony 4.

Here's the error i have when i reach the 'download' part of the installation : `php bin/console ckeditor:install`

![image](https://user-images.githubusercontent.com/19261877/36893984-479c6fb8-1e0a-11e8-89c5-de2083307a44.png)

## Setup 
- Symfony 4.0.4
- Used flex recipe :  `composer require hillrange/ckeditor`

INFO: i know this is work in progress :)

**Comment by crayner** [comment]
I have not been able to reproduce this error, but it has been reported twice now.  Version 0.1.14 is now on Github and it has a fix that checks for the array mentioned and sets a string.  May cause me grief later, but it still installs correctly here with the changes.  (Now version 0.1.16 as I played with why the tag was in front of the changes.)

**Comment by AntseN** [comment]
@crayner Well in order to use your bundle, i copied all files 
from `/vendor/hillrange/ckeditor/Resources/public` 
to `/myproject/public/bundles/hillrangeckeditor/ ` by hand. 
I mean you could add this 'fix' in the readme (as a side note if someone encounters the same issue) until you reach a stable release.

Thanks anyways.

**Comment by crayner** [comment]
I found the issue and have made a permanent repair of the question.  Should not be an issue now.
