### ISSUE TITLE
Install / Update / remove errors

### ISSUE THREAD

**Issue by AntseN** [crayner/CKEditor#4]
Hi there,

Here's an error i'm getting when installing or updating this package with composer :
Using symfony 4.0.4 & Composer 1.6.3

![image](https://user-images.githubusercontent.com/19261877/37894984-4c04447a-30e0-11e8-823b-359344e34bde.png)
![image](https://user-images.githubusercontent.com/19261877/37895132-b6eb4ec8-30e0-11e8-9aad-9ee11c739f43.png)

Here's another one when i go for a composer remove : 
![image](https://user-images.githubusercontent.com/19261877/37895211-ed9db8ac-30e0-11e8-8e1c-bd8f6852489b.png)

**Comment by crayner** [comment]
Thanks for the issue.  

This is an issue with the PHP package on your system.  You will need to install the ZIP package with PHP as per the instructions in the [PHP Documentation.](http://php.net/manual/en/zip.setup.php)  I will update the installation documentation to ensure that ZIP is installed.

**Comment by AntseN** [comment]
Yes when i first tested i was under windows, so it was installed by default.
