### ISSUE TITLE
I use this package for SonataFormatterBundle 

### ISSUE THREAD

**Issue by tinozak** [crayner/CKEditor#5]
This package is very good, thank you.

When i install SonataFormatterBundle, it still require egeloen/ckeditor-bundle, but egeloen/ckeditor-bundle can not use for symfony4.

How can i install your package?

Thanks.

**Comment by crayner** [comment]
Hi,  In the  SonataFormatterBundle composer.json replace the `"egeloen/ckeditor-bundle": "^4.0 || ^5.0",` with `"hillrange/ckeditor": "^0.1", `

This will load the package, but the SonataFormatterBundle may test for the egeloen/ckeditor-bundle and you may need to edit those as well.

**Comment by crayner** [comment]
Closed as not ckeditor issue.

**Comment by tinozak** [comment]
Thanks for your replay.
