### ISSUE TITLE
Default form type 'ckeditor' for easy-admin-bundle

### ISSUE THREAD

**Issue by Bosswell** [crayner/CKEditor#6]
As you get installed easy-admin-bundle you have to manually make a change in file
`\vendor\easycorp\easyadmin-bundle\src\Form\Util\LegacyFormHelper.php`
if you want to use type 'ckeditor'.

From
`'ckeditor' => 'Ivory\\CKEditorBundle\\Form\\Type\\CKEditorType',`

to 
`'ckeditor' => 'Hillrange\\CKEditor\\Form\\CKEditorType',`

**Comment by crayner** [comment]
Entirely possible, as easy-admin-bundle is not part of Hillreange/CKEditor.
